### ISSUE TITLE
mapa mental

### ISSUE THREAD

**Issue by Sandoval6** [SistemasTecTlaxiaco/actividad-4-mapa-mental-calidad-de-software-Sandoval6#1]
[mapa mental Proyectos de Software.pdf](https://github.com/user-attachments/files/17103150/mapa.mental.Proyectos.de.Software.pdf)

**Comment by josealfredo79** [comment]
Calificacion 17, hace falta jerarquizacion en el mapa mental, las referencias tambien hacen falta...
